package gobblets.IHM;

public enum Avertissement {
    TONTOUR,
    CHOIXACTION,
    CHOIXTAILLE,
    NOMJOUEUR,
    COULEURJOUEUR,
    CHOIXORIGIN,
    CHOIXDESTINATION,
    SAISIECOORDONNEES,
    SAISIECOORDONNEE1,
    SAISIECOORDONNEE2,
    MAISON,
    CHOIXTYPEJOUEUR;

    Avertissement() {}
}