package gobblets.IHM;

public enum Avertissement {
    TONTOUR,
    CHOIXACTION,
    CHOIXTAILLE,
    NOMJOUEUR,
    COULEURJOUEUR,
    CHOIXORIGIN,
    CHOIXDESTINATION,
    SAISIEJOUEUR,
    SAISIECOORDONNEES,
    SAISIECOORDONNEE1,
    SAISIECOORDONNEE2,
    MAISON,
    CHOIXTYPEJOUEUR,
    ANNULATIONSAISIE,
    CONFIRMER,
    AUCUNESAUVEGARDE,
    APPUYERSURENTREE,
    ENTRERLENOMDELASAUVEGARDE,
    CONTINUER,
    FICHIERDEJAEXISTANT,
    SUPPRIMER;

    Avertissement() {}
}