package gobblets.IHM;

public enum Erreur {
    PASDEPIECEDISPONIBLE,
    PASTAPIECE,
    CASEBLOQUE,
    ARGUMENTINCORECT,
    PASDEPIECEICI,
    PASDETAILLEDISPONIBLE,
    DIAGONALEINCORECTE,
    ORIGINVIDE;

    Erreur() {}
}